version: '3.5'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-vz
    ports:
      - '8001:8001'
    volumes:
      -  .:/app
      -  /app/node_modules
    
